# Generated by Django 3.0.5 on 2020-04-18 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestDemo',
            new_name='test_demo',
        ),
    ]
