# Generated by Django 3.0.5 on 2020-04-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_auto_20200419_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='movie_id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
