# Generated by Django 3.0.5 on 2020-04-19 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_auto_20200419_0247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieInfo',
        ),
    ]
