# Generated by Django 3.0.5 on 2020-04-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0006_delete_movieinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('movie_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('rate', models.CharField(max_length=32)),
                ('movie_url', models.CharField(max_length=128)),
                ('cover_url', models.CharField(max_length=128)),
                ('cover_x', models.IntegerField()),
                ('cover_y', models.IntegerField()),
                ('directors', models.CharField(max_length=128)),
                ('actors', models.CharField(max_length=256)),
                ('duration', models.CharField(max_length=32)),
                ('region', models.CharField(max_length=32)),
                ('types', models.CharField(max_length=128)),
                ('release_year', models.CharField(max_length=63)),
                ('create_time', models.DateTimeField(max_length=63)),
            ],
        ),
    ]
