# Generated by Django 3.0.5 on 2020-04-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0009_movieinfo_testdemo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='actors',
            field=models.CharField(max_length=2048),
        ),
    ]
